spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#logging:
#  level:
#    edu.hfut: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl