spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      write-dates-as-timestamps: true
  elasticsearch:
    uris: http://cloud100:9200
    username: elastic
    password: 123456
