spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      write-dates-as-timestamps: true
  elasticsearch:
    uris: http://wolves.vip:9200
    username: elastic
    password: 123456
mybatis-plus:
  type-aliases-package: edu.hfut.innovate.community.entity
  configuration-properties:
    org.apache.ibatis.parsing.PropertyParser.enable-default-value: true
#  configuration:
#    lazy-loading-enabled: true
#  type-handlers-package: edu.hfut.innovate.community.config